/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreePlantingRouteImport } from './routes/tree-planting'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotesSlugRouteImport } from './routes/notes.$slug'

const TreePlantingRoute = TreePlantingRouteImport.update({
  id: '/tree-planting',
  path: '/tree-planting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesSlugRoute = NotesSlugRouteImport.update({
  id: '/notes/$slug',
  path: '/notes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tree-planting': typeof TreePlantingRoute
  '/notes/$slug': typeof NotesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tree-planting': typeof TreePlantingRoute
  '/notes/$slug': typeof NotesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tree-planting': typeof TreePlantingRoute
  '/notes/$slug': typeof NotesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tree-planting' | '/notes/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tree-planting' | '/notes/$slug'
  id: '__root__' | '/' | '/tree-planting' | '/notes/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TreePlantingRoute: typeof TreePlantingRoute
  NotesSlugRoute: typeof NotesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tree-planting': {
      id: '/tree-planting'
      path: '/tree-planting'
      fullPath: '/tree-planting'
      preLoaderRoute: typeof TreePlantingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$slug': {
      id: '/notes/$slug'
      path: '/notes/$slug'
      fullPath: '/notes/$slug'
      preLoaderRoute: typeof NotesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TreePlantingRoute: TreePlantingRoute,
  NotesSlugRoute: NotesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
